name: Python App Release Build

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  # ... (build-desktop job remains unchanged) ...
  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Create executable (PyInstaller)
        run: |
          pyinstaller --onefile --windowed --name "CALCULATOR" CALCULATOR.py
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CALCULATOR-${{ matrix.os }}
          path: dist/CALCULATOR${{ startsWith(matrix.os, 'windows') && '.exe' || '' }}


  # --- Android APK Build (Kivy + Buildozer) ---
  build-android-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # --- Corrected Android SDK Setup ---
      - name: Set up Android SDK
        uses: nttld/setup-android@v1 # <--- CHANGED FROM @v1.3 TO @v1
        with:
          android-version: 30 # Or 33. This should generally match your buildozer.spec's android.api
          build-tools-version: 30.0.3 # Or 33.0.0. A specific stable version is good.
          sdk-tools-version: 6858069 # Latest stable command-line tools version
      # ---------------------------------------------

      - name: Install Buildozer, Kivy, and Cython
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          pip install cython
          pip install buildozer kivy

      - name: Initialize Buildozer spec file (if not already present)
        run: |
          # buildozer init # Only run if buildozer.spec is NOT in your repo
          # Example modifications (ensure these are in your committed buildozer.spec)
          # sed -i 's/^requirements = python3,kivy$/requirements = python3,kivy,math/' buildozer.spec
          # sed -i 's/^#android.permissions =$/android.permissions = INTERNET,VIBRATE/' buildozer.spec
          # sed -i 's/^title = My Application$/title = Your Kivy Android App/' buildozer.spec
          # sed -i 's/^package.name = org.test.myapp$/package.name = com.example.yourkivyapp/' buildozer.spec
          # sed -i 's/^package.domain = test.org$/package.domain = yourdomain.com/' buildozer.spec

      - name: Build Android APK
        run: |
          buildozer android debug

      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: CALCULATOR-Android-APK
          path: bin/*.apk
