name: Python App Release Build

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  # --- Desktop Builds (Windows, macOS, Linux) using PyInstaller ---
  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9'] # Or your preferred Python version

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller # Tkinter and math are standard, no separate install needed

      - name: Create executable (PyInstaller)
        run: |
          pyinstaller --onefile --windowed --name "CALCULATOR" CALCULATOR.py
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: YourAppName-${{ matrix.os }}
          path: dist/YourAppName${{ startsWith(matrix.os, 'windows') && '.exe' || '' }}


  # --- Android APK Build (Kivy + Buildozer) ---
  build-android-apk:
    runs-on: ubuntu-latest # Buildozer requires a Linux environment
    # Only run this job if the primary script is Kivy-compatible or you have a Kivy port.
    # Otherwise, this job will fail trying to include Tkinter.

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11' # Buildozer often requires a specific JDK version

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Buildozer, Kivy, and Cython # <-- Changed step name for clarity
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          pip install cython # <--- ADDED THIS LINE
          pip install buildozer kivy

      - name: Initialize Buildozer spec file (if not already present)
        run: |
          buildozer init
          # If you have specific Android app settings, modify buildozer.spec here or ensure it's committed
          # Example modification (uncomment if you need to set requirements or permissions in CI)
          # sed -i 's/^requirements = python3,kivy$/requirements = python3,kivy,math/' buildozer.spec
          # sed -i 's/^#android.permissions =$/android.permissions = INTERNET,VIBRATE/' buildozer.spec
          # sed -i 's/^title = My Application$/title = Your Kivy Android App/' buildozer.spec
          # sed -i 's/^package.name = org.test.myapp$/package.name = com.example.yourkivyapp/' buildozer.spec
          # sed -i 's/^package.domain = test.org$/package.domain = yourdomain.com/' buildozer.spec

      - name: Build Android APK
        run: |
          buildozer android debug

      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: YourAppName-Android-APK
          path: bin/*.apk # Buildozer places the APK in the 'bin' directory
